apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app.kubernetes.io/name: spring-demo
    ports:
      - protocol: "TCP"
        port: 8080
        targetPort: 8080
    type: Nodeport
